export const PERSON_QUERY_BASE = "PERSON_QUERY_BASE";
export const COURSER_QUERY_BANNER = "COURSER_QUERY_BANNER";
export const COURSER_QUERY_LIST = "COURSER_QUERY_LIST";
export const COURSE_UNPAY = "COURSE_UNPAY";
export const COURSE_PAY = "COURSE_PAY";
export const COURSE_HANDLE = "COURSE_HANDLE";